feature: Add gemini backend
dustinblackman/oatmeal pull request #52
Opened 2024-03-03 18:41 UTC by aislasq

This is the implementation of the Gemini API. 

I've been using for general questions outside neovim and it works well, I think it would greatly benefit from the custom system prompts.

- [X] Implement trait for new backend.
- [X] Update the [BackendName](https://github.com/dustinblackman/oatmeal/blob/main/src/domain/models/backend.rs) enum with your new Backend name.
- [X] Update the [BackendManager](https://github.com/dustinblackman/oatmeal/blob/main/src/infrastructure/backends/mod.rs) to provide your new backend.
- [X] Write tests
- [X] Update Readme
- [X] Update config

2024-03-09 18:57 UTC, dustinblackman requested changes
Hey there! Thanks for the PR, this is really exciting. I haven't had the chance to play with Gemini yet, and it'll be sick for my first experience to be in Oatmeal. 

Just got a few comments and questions, mostly around getting tests fixed up.

2024-03-10 20:21 UTC, aislasq commented on src/infrastructure/backends/gemini.rs
> +            model = Config::get(ConfigKey::Model),
Is there a possibility to get more info on the test? I am doing the Config::set in the test exactly as you mentioned:
https://github.com/aislasq/oatmeal/blob/5f4fd4f89b0634060e456ef9b3e4144167ddfeee/src/infrastructure/backends/gemini_test.rs#L54

2024-03-10 20:21 UTC, aislasq commented on src/infrastructure/backends/gemini.rs
> +    // output_token_limit: u32,
Yes, but we can remove them and add them later when needed.

2024-03-10 20:21 UTC, aislasq commented on src/infrastructure/backends/gemini_test.rs
> +    let body = [
Believe it or not, Google's stream implementation is sending a 'prettified' json object line by line. If you take a closer look I am not serializing the object, I am appending it by line to get something like this:
```json
{
  "contents": [
    {
      "parts" : [{
        "text": "Hello"
      }]
    },
    {
      "parts": [{
        "text": "World"
      }]
    }
  ]
}
```

2024-03-10 20:21 UTC, aislasq commented on config.example.toml
> +# Gemini API token when using the OpenAI backend.
Must fix before merging

2024-03-10 20:36 UTC, aislasq commented
The lint is failing because my formatter is changing it on save, I am using rustfmt 1.6.0-stable (79e9716c 2023-11-13). Should I use a different one?

2024-03-10 21:51 UTC, aislasq commented on src/infrastructure/backends/gemini.rs
> +            model = Config::get(ConfigKey::Model),
I know what's going on, I'm an idiot. Of course it's going to fail, it expects an env variable. Give me a minute to check if I can generate a new one so you can add it to the secrets in the repo.

2024-03-11 02:20 UTC, aislasq commented on src/infrastructure/backends/gemini_test.rs
> +    let body = [
Changed the array to a raw string. 
This is the official documentation:
https://ai.google.dev/tutorials/rest_quickstart#stream_generate_content

2024-03-11 02:26 UTC, dustinblackman commented on src/infrastructure/backends/gemini.rs
> +            model = Config::get(ConfigKey::Model),
The github actions test suite is using `nextest`, this runs tests in parallel process' where memory will be different for each test. You have `Config:set` being used in one test, but it's gotta be use in all your [healthcheck tests](https://github.com/aislasq/oatmeal/blob/5f4fd4f89b0634060e456ef9b3e4144167ddfeee/src/infrastructure/backends/gemini_test.rs#L74C10-L74C32).

2024-03-11 02:28 UTC, dustinblackman commented
> The lint is failing because my formatter is changing it on save, I am using rustfmt 1.6.0-stable (79e9716c 2023-11-13). Should I use a different one?

The project is using a nightly version of rustfmt to gain access to other features I wanted. You can run `cargo cmd lint-fix` to fix everything before committing. If the command fails, you may need to take a look at the [setup guide](https://github.com/dustinblackman/oatmeal?tab=readme-ov-file#setup) to get all the dependencies setup, otherwise I should have a devcontainer available tomorrow if that's a workflow you enjoy using. :)

2024-03-11 03:52 UTC, aislasq commented on src/infrastructure/backends/gemini.rs
> +            model = Config::get(ConfigKey::Model),
Done, let me check the linter so you can re-run the tests. Thanks!

2024-03-12 00:54 UTC, dustinblackman approved these changes
Really appreciate this, code looks great and I'm excited to play with it more. Great job!

2024-03-12 00:54 UTC, merged